### ISSUE TITLE
Offset Height

### ISSUE THREAD

**Issue by onebeat** [rudolfrck/iscroll-stickyheaders#3]
Hello, i found your plugin and it is just what i wanted but with slight problem regarding sticky header.

I have list of events that are using iscroll ofcourse and have hidden div that is opened when clicked on button and then i use iscroll to scoll description.

Problem is that header part that need to be sticky is sticky only for 58px after that it goes back.

If i remove this part of code

else if (translateY > header.maxY) {
                    // Make sure it never exceeds it's max allowed position
                    translateY = 0;
                }
it works just fine but then when i close and open another event in the list and close it again all events are stuck with this value transform: translate(0px, 196px)
depending where is event clicked.

I can setup demo so you can check it out...

**Comment by rudolfrck** [comment]
Since there is no more information, I'm closing this.
