### ISSUE TITLE
Offset from top of viewport

### ISSUE THREAD

**Issue by maximilianschmidt** [rudolfrck/iscroll-stickyheaders#8]
hi there,

thanks a lot for the plugin, really helpful! one question though:

is it possible to set a offset for the sticky headers so they are not sticky at the very top of my browser? lets say i have element at x=0 / y=0 with a height of 300px and i want the sticky headers to stick to the bottom of that element (300px from the top of the viewport)? 

maybe something like `scroll.enableStickyHeaders('.selector', offsetFromTopInPixels);` ?

cheers

max

**Comment by rudolfrck** [comment]
That shouldn't be too hard to implement as a configurable option.
I'll see what I can do, otherwise I'm happy for PRs.

**Comment by maximilianschmidt** [comment]
thanks a lot!

**Comment by maximilianschmidt** [comment]
just solved it, but i dont really know how to do a pull request since im quite new to github.

**Comment by rudolfrck** [comment]
Sounds great! I've been quite busy and hadn't had the time to look at it just yet.

To fork, press the "Fork" button to the top right. Then you get your own copy of the entire repository.
Then you clone that repository locally, apply your changes, commit and push it to your fork.

Then you go to "Pull requests" and press "New pull request" on the top right.

**Comment by rudolfrck** [comment]
Read more about forks here:
https://help.github.com/articles/fork-a-repo/

**Comment by maximilianschmidt** [comment]
thank you! i will do that.
